version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: f1-dashboard-backend
    container_name: f1-dashboard-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - f1-dashboard

  db:
    image: mysql:8.0
    ports:
      - "3309:3309"
    environment:
      MYSQL_DATABASE: f1_dashboard
      MYSQL_USER: f1user
      MYSQL_PASSWORD: f1password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - f1-dashboard

  nginx:
    image: nginx:alpine
    container_name: f1-dashboard-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: f1_dashboard
      DB_USERNAME: f1user
      DB_PASSWORD: f1password
    networks:
      - f1-dashboard

networks:
  f1-dashboard:
    driver: bridge

volumes:
  dbdata:
    driver: local
