apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-vue-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f1-vue-frontend
  template:
    metadata:
      labels:
        app: f1-vue-frontend
    spec:
      containers:
        - name: f1-vue-frontend
          image: f1-vue-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: VUE_APP_API_URL
              value: https://f1-backend.local/api
