apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: ZjF1c2Vy  # base64 encoded 'f1user'
  password: ZjFwYXNzd29yZA==  # base64 encoded 'f1password'
  root-password: cm9vdHBhc3N3b3Jk  # base64 encoded 'rootpassword'